Improve documentation for graceful shutdown feature of Dubbo3
apache/dubbo-website pull request #1104
Opened 2022-06-15 12:13 UTC by cdfive

完善文档，Dubbo3.x新版本，高级特性和用法——其他——优雅停机 https://github.com/apache/dubbo-awesome/issues/62

2022-06-16 12:18 UTC, CrazyHZM requested changes

2022-06-16 12:18 UTC, CrazyHZM commented on content/zh/docs3-building/java-sdk/advanced-features-and-usage/others/graceful-shutdown.md
> +* 特性说明
使用Markdown语法，比如`# 特性说明`

2022-06-16 12:18 UTC, CrazyHZM commented on content/zh/docs3-building/java-sdk/advanced-features-and-usage/others/graceful-shutdown.md
> +一个Dubbo服务可能即作为服务提供者，又是服务消费者，当服务停止时：
`即` 改为 `既`

2022-06-16 12:18 UTC, CrazyHZM commented on content/zh/docs3-building/java-sdk/advanced-features-and-usage/others/graceful-shutdown.md
> +该参数可在 dubbo.properties 文件里配置，例如：配置为 30 秒。
这个配置建议索引一下对应的文档链接

2022-06-16 14:16 UTC, cdfive commented on content/zh/docs3-building/java-sdk/advanced-features-and-usage/others/graceful-shutdown.md
> +该参数可在 dubbo.properties 文件里配置，例如：配置为 30 秒。
请问用这个链接可以吗 https://dubbo.apache.org/zh/docs/references/configuration/properties/

2022-06-17 04:02 UTC, CrazyHZM commented on content/zh/docs3-building/java-sdk/advanced-features-and-usage/others/graceful-shutdown.md
> +该参数可在 dubbo.properties 文件里配置，例如：配置为 30 秒。
> 请问用这个链接可以吗 https://dubbo.apache.org/zh/docs/references/configuration/properties/ 在官方文档里没能找到能看所有配置项的文档

这个是旧文档的链接，后续再做补充和索引。

2022-06-17 04:02 UTC, CrazyHZM approved these changes

2022-06-17 04:02 UTC, merged