fix duplicate mail in mailing-list-subscription-guide_dev.md
apache/dubbo-website pull request #951
Opened 2021-09-15 07:56 UTC by yanghesong

Raw URL of mail https://github.com/apache/dubbo/issues/1393) (#948)

2021-09-15 14:21 UTC, wangchengming666 approved these changes
LGTM

2021-09-20 03:14 UTC, horizonzy reviewed
now dubbo already graduated, should not use incubator.

2021-09-20 14:08 UTC, AlbumenJ requested changes

2021-09-20 14:08 UTC, AlbumenJ commented on content/zh/contribution-guidelines/contributor/mailing-list-subscription-guide_dev.md
> +> 请注意：dev@dubbo.apache.org和dev@dubbo.incubator.apache.org都是有效的, 您可以订阅它们中的任何一个。
please remove `dev@dubbo.incubator.apache.org`

2021-09-21 01:49 UTC, yanghesong commented on content/zh/contribution-guidelines/contributor/mailing-list-subscription-guide_dev.md
> +> 请注意：dev@dubbo.apache.org和dev@dubbo.incubator.apache.org都是有效的, 您可以订阅它们中的任何一个。
Done

2021-09-21 15:59 UTC, AlbumenJ requested changes

2021-09-21 15:59 UTC, AlbumenJ commented on content/zh/contribution-guidelines/contributor/mailing-list-subscription-guide_dev.md
> +> 请注意：dev@dubbo.apache.org是有效的。dev@dubbo.incubator.apache.org已经不再适用。
`适用` -> `使用`

2021-09-22 02:23 UTC, yanghesong commented on content/zh/contribution-guidelines/contributor/mailing-list-subscription-guide_dev.md
> +> 请注意：dev@dubbo.apache.org是有效的。dev@dubbo.incubator.apache.org已经不再适用。
Done

2021-09-22 08:12 UTC, merged